[tool.poetry]
name = "opsi-cli"
version = "4.2.0.2"
description = "opsi command line interface"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
authors = ["uib GmbH <info@uib.de>"]
maintainers = ["uib GmbH <info@uib.de>"]
packages = [
	{ include = "opsicli" }
]

[[tool.poetry.source]]
name = "uib"
url = "http://pypi.uib.gmbh:8080/simple/"

[tool.poetry.dependencies]
"ruamel.yaml" = "^0.17"
click = "^8.1"
msgpack = "^1.0"
orjson = "^3.6"
pipreqs = "^0.4"
python = "^3.10,<3.12"
python-opsi-common = "^4.2"
rich-click = "^1.3"

[tool.poetry.dev-dependencies]
flake8 = "^5.0"
isort = "^5.10"
mypy = "^0.990"
pyinstaller = "^5.5"
pylint = "^2.6"
pytest = "^7.1"
pytest-cov = "^4.0"
pytest-coverage = "^0.0"
tan = "^22.8"

[tool.poetry.scripts]
opsi-cli = "opsicli.__main__:main"

[tool.black]
line-length = 140
target-version = ['py310']
use-tabs = true

[tool.isort]
profile = "black"
indent = "\t"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
