[tool.poetry]
name = "opsi-cli"
version = "0.1.0"
description = "opsi command line interface"
homepage = "https://www.opsi.org"
license = "AGPL-3.0"
authors = ["uib GmbH <info@uib.de>"]
maintainers = ["uib GmbH <info@uib.de>"]
packages = [
	{ include = "opsicli" }
]

[[tool.poetry.source]]
name = "uib"
url = "http://pypi.uib.gmbh:8080/simple/"

[tool.poetry.dependencies]
python = "^3.10,<3.11"
click = "^8.0"
pipreqs = "^0.4"
python-opsi-common = "^4.2"
rich-click = "^1.2"
"ruamel.yaml" = "^0.17"
orjson = "^3.6"
msgpack = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2"
opsi-dev-tools = "^1.1"
pyinstaller = "^4.10"
pylint = "^2.6"
flake8 = "^4.0"
pytest-cov = "^3.0"
mypy = "^0.931"
tan = "^21.14"
pytest-coverage = "^0.0"
isort = "^5.10"

[tool.poetry.scripts]
opsi-cli = "opsicli.__main__:main"

[tool.black]
line-length = 140
target-version = ['py310']
use-tabs = true

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
