base_dir=$(dirname $(dirname $(readlink -f $0)))
docker_dir=${base_dir}/docker
env_template_file=${docker_dir}/env.template
env_file=${docker_dir}/.env
env_file_server=${docker_dir}/opsi-server/.env
env_file_cli=${docker_dir}/opsi-cli-dev/.env

echo "Base directory: ${base_dir}"

echo "Writing env file: ${env_file}"

if [ -e $env_file ]; then
	set -o allexport
	. $env_file
	set +o allexport
fi

LOCAL_WORKSPACE_DIR="${base_dir}"
[ -d "${LOCAL_WORKSPACE_DIR}" ] || LOCAL_WORKSPACE_DIR="."
echo "Local workspace dir: ${LOCAL_WORKSPACE_DIR}"

[ -z "${OPSILICSRV_URL}" ] && echo "Please set OPSILICSRV_URL in $env_file" >&2
[ -z "${OPSILICSRV_TOKEN}" ] && echo "Please set OPSILICSRV_TOKEN in $env_file" >&2

cat <<EOF > $env_file
# Generated by docker/create_env.sh

# Content from $env_template_file
EOF
cat $env_template_file >> $env_file

cat <<EOF >> $env_file

# Dynamically added content
LOCAL_WORKSPACE_DIR="${LOCAL_WORKSPACE_DIR}"
USER="$(id -u -n)"
DEV_USER="$(id -u -n)"
DEV_UID=$(id -u)
OPSILICSRV_URL="${OPSILICSRV_URL}"
OPSILICSRV_TOKEN="${OPSILICSRV_TOKEN}"
EOF

rm -f $env_file_server
rm -f $env_file_cli
cp $env_file $env_file_server
cp $env_file $env_file_cli
